
-- Seed model_mesh_mappings with all hardcoded anatomy data from AdvancedAnatomyViewer
-- Using model_url as logical model ID, mesh_key as the mesh name, and facts as full JSON blob

INSERT INTO public.model_mesh_mappings (model_url, mesh_key, name, summary, icon, system, facts) VALUES
-- ═══ SKULL MODEL ═══
('skull', 'Frontal', 'Frontal Bone', 'עצם המצח', '🧠', 'cranium', '{"displayNameHe":"עצם המצח","latinName":"Os frontale","function":"Protects the frontal lobe, forms orbital roof","functionHe":"מגן על האונה הקדמית, מהווה את תקרת ארובת העין","facts":["Forms the forehead","Contains frontal sinuses"],"factsHe":["מהווה את המצח","מכיל את הסינוסים המצחיים"],"diseases":["Frontal sinusitis","Frontal fracture"],"diseasesHe":["דלקת סינוסים מצחית","שבר מצחי"]}'),
('skull', 'Occipital', 'Occipital Bone', 'עצם העורף', '🧠', 'cranium', '{"displayNameHe":"עצם העורף","latinName":"Os occipitale","function":"Forms the back/base of the skull, protects cerebellum","functionHe":"מהווה את חלקה האחורי והתחתון של הגולגולת, מגן על המוח הקטן","facts":["Contains the foramen magnum","Articulates with the atlas (C1)"],"factsHe":["מכיל את הפורמן מגנום - פתח חוט השדרה","מתחבר לחוליה הראשונה"],"diseases":["Occipital neuralgia","Chiari malformation"],"diseasesHe":["נוירלגיה עורפית","מום קיארי"]}'),
('skull', 'Sphenoid', 'Sphenoid Bone', 'עצם הפרפר', '🧠', 'cranium', '{"displayNameHe":"עצם הפרפר","latinName":"Os sphenoidale","function":"Keystone of skull base; protects pituitary gland","functionHe":"אבן הפינה של בסיס הגולגולת; מגנה על בלוטת יותרת המוח","facts":["Called the butterfly bone","Articulates with all cranial bones"],"factsHe":["נקראת עצם הפרפר בשל צורתה","מתחברת לכל עצמות הגולגולת"],"diseases":["Pituitary adenoma","Sphenoid sinusitis"],"diseasesHe":["אדנומה של יותרת המוח","דלקת סינוס ספנואידלי"]}'),
('skull', 'Ethmoid', 'Ethmoid Bone', 'עצם המסננת', '🧠', 'cranium', '{"displayNameHe":"עצם המסננת","latinName":"Os ethmoidale","function":"Separates nasal cavity from brain","functionHe":"מפרידה בין חלל האף למוח","facts":["Lightest skull bone","Contains olfactory foramina"],"factsHe":["העצם הקלה ביותר בגולגולת","מכילה פתחים לעצבי הריח"],"diseases":["Ethmoid sinusitis","Epistaxis"],"diseasesHe":["דלקת סינוס אתמואידלי","דימום מהאף"]}'),
('skull', 'Left_zygomatic', 'Left Zygomatic', 'עצם לחי שמאל', '😮', 'face', '{"displayNameHe":"עצם לחי שמאל","latinName":"Os zygomaticum sinistrum","function":"Forms cheekbone and orbital wall","functionHe":"מהווה את עצם הלחי ודופן ארובת העין","facts":["Forms the cheek arch","Articulates with 4 bones"],"factsHe":["מהווה את קשת הלחי","מתחברת ל-4 עצמות"],"diseases":["Zygomatic fracture"],"diseasesHe":["שבר בעצם הלחי"]}'),
('skull', 'Right_zygomatic', 'Right Zygomatic', 'עצם לחי ימין', '😮', 'face', '{"displayNameHe":"עצם לחי ימין","latinName":"Os zygomaticum dextrum","function":"Forms cheekbone and orbital wall","functionHe":"מהווה את עצם הלחי ודופן ארובת העין","facts":["Mirror of left zygomatic","Key to facial width"],"factsHe":["מראה של עצם הלחי השמאלית","משפיעה על רוחב הפנים"],"diseases":["Zygomatic fracture"],"diseasesHe":["שבר בעצם הלחי"]}'),
('skull', 'Right_Parietal', 'Right Parietal', 'עצם קדקוד ימין', '🧠', 'cranium', '{"displayNameHe":"עצם קדקוד ימין","latinName":"Os parietale dextrum","function":"Forms roof and sides of cranium","functionHe":"מהווה את גג הגולגולת ודפנותיה","facts":["Forms the top-side of the skull","Contains the parietal foramen"],"factsHe":["מהווה את חלקה העליוני-צידי של הגולגולת","מכילה את הפורמן הקדקודי"],"diseases":["Parietal fracture"],"diseasesHe":["שבר בעצם הקדקוד"]}'),
('skull', 'Left_Parietal', 'Left Parietal', 'עצם קדקוד שמאל', '🧠', 'cranium', '{"displayNameHe":"עצם קדקוד שמאל","latinName":"Os parietale sinistrum","function":"Forms roof and sides of cranium","functionHe":"מהווה את גג הגולגולת ודפנותיה","facts":["Articulates with all cranial bones","Convex outer surface"],"factsHe":["מתחברת לכל עצמות הגולגולת","משטח חיצוני קמור"],"diseases":["Parietal lobe stroke"],"diseasesHe":["שבץ באונה הקדקודית"]}'),
('skull', 'Right_temporal', 'Right Temporal', 'עצם רקה ימין', '🧠', 'cranium', '{"displayNameHe":"עצם רקה ימין","latinName":"Os temporale dextrum","function":"Houses ear canal and inner ear","functionHe":"מכילה את תעלת האוזן והאוזן הפנימית","facts":["Contains inner ear structures","Has the mastoid process"],"factsHe":["מכילה את מבני האוזן הפנימית","כוללת את התוספת המסטואידית"],"diseases":["Temporal bone fracture","Mastoiditis"],"diseasesHe":["שבר בעצם הרקה","דלקת המסטואיד"]}'),
('skull', 'Left_temporal', 'Left Temporal', 'עצם רקה שמאל', '🧠', 'cranium', '{"displayNameHe":"עצם רקה שמאל","latinName":"Os temporale sinistrum","function":"Houses ear canal and inner ear","functionHe":"מכילה את תעלת האוזן והאוזן הפנימית","facts":["Contains cochlea and vestibular apparatus","Styloid process anchors tongue muscles"],"factsHe":["מכילה את השבלול ומנגנון שיווי המשקל","תוספת הסטילואיד מעגנת שרירי לשון"],"diseases":["Temporal arteritis"],"diseasesHe":["דלקת עורק רקתי"]}'),
('skull', 'Right_lacrimal', 'Right Lacrimal', 'עצם דמעה ימין', '😮', 'face', '{"displayNameHe":"עצם דמעה ימין","latinName":"Os lacrimale dextrum","function":"Houses the nasolacrimal duct","functionHe":"מכילה את צינור הדמעות","facts":["Smallest facial bone","Contains nasolacrimal groove"],"factsHe":["העצם הקטנה ביותר בפנים","מכילה את תעלת הדמעות"],"diseases":["Dacryocystitis"],"diseasesHe":["דלקת שק הדמעות"]}'),
('skull', 'Left_lacrimal', 'Left Lacrimal', 'עצם דמעה שמאל', '😮', 'face', '{"displayNameHe":"עצם דמעה שמאל","latinName":"Os lacrimale sinistrum","function":"Houses the nasolacrimal duct","functionHe":"מכילה את צינור הדמעות","facts":["Smallest facial bone","Part of medial orbital wall"],"factsHe":["העצם הקטנה ביותר בפנים","חלק מדופן ארובת העין הפנימית"],"diseases":["Dacryocystitis"],"diseasesHe":["דלקת שק הדמעות"]}'),
('skull', 'Right_max', 'Right Maxilla', 'לסת עליונה ימין', '😮', 'face', '{"displayNameHe":"לסת עליונה ימין","latinName":"Maxilla dextra","function":"Forms upper jaw, holds teeth, forms hard palate","functionHe":"מהווה את הלסת העליונה, מחזיקה שיניים, מהווה את החיך הקשה","facts":["Holds upper teeth","Largest facial bone besides mandible"],"factsHe":["מחזיקה שיניים עליונות","העצם הגדולה ביותר בפנים אחרי הלסת התחתונה"],"diseases":["Maxillary sinusitis","Cleft palate"],"diseasesHe":["דלקת סינוס מקסילרי","חך שסוע"]}'),
('skull', 'Left_max', 'Left Maxilla', 'לסת עליונה שמאל', '😮', 'face', '{"displayNameHe":"לסת עליונה שמאל","latinName":"Maxilla sinistra","function":"Forms upper jaw, holds teeth","functionHe":"מהווה את הלסת העליונה, מחזיקה שיניים","facts":["Holds upper teeth","Fuses with right maxilla at midline"],"factsHe":["מחזיקה שיניים עליונות","מתאחה עם הלסת הימנית באמצע"],"diseases":["Cleft lip and palate"],"diseasesHe":["שפה וחיך שסועים"]}'),
('skull', 'right_nasal', 'Right Nasal', 'עצם אף ימין', '😮', 'face', '{"displayNameHe":"עצם אף ימין","latinName":"Os nasale dextrum","function":"Forms the bridge of the nose","functionHe":"מהווה את גשר האף","facts":["Small rectangular bone","Forms the nasal bridge"],"factsHe":["עצם מלבנית קטנה","מהווה את גשר האף"],"diseases":["Nasal fracture"],"diseasesHe":["שבר באף"]}'),
('skull', 'left_nasal', 'Left Nasal', 'עצם אף שמאל', '😮', 'face', '{"displayNameHe":"עצם אף שמאל","latinName":"Os nasale sinistrum","function":"Forms the bridge of the nose","functionHe":"מהווה את גשר האף","facts":["Small rectangular bone","Often asymmetric"],"factsHe":["עצם מלבנית קטנה","לרוב אסימטרית"],"diseases":["Nasal fracture"],"diseasesHe":["שבר באף"]}'),
('skull', 'right_palatine', 'Right Palatine', 'עצם חיך ימין', '😮', 'face', '{"displayNameHe":"עצם חיך ימין","latinName":"Os palatinum dextrum","function":"Forms posterior hard palate","functionHe":"מהווה את השליש האחורי של החיך הקשה","facts":["L-shaped bone","Forms posterior hard palate"],"factsHe":["עצם בצורת L","מהווה את החלק האחורי של החיך הקשה"],"diseases":["Cleft palate"],"diseasesHe":["חיך שסוע"]}'),
('skull', 'left_palatine', 'Left Palatine', 'עצם חיך שמאל', '😮', 'face', '{"displayNameHe":"עצם חיך שמאל","latinName":"Os palatinum sinistrum","function":"Forms posterior hard palate","functionHe":"מהווה את השליש האחורי של החיך הקשה","facts":["L-shaped bone","Contains greater palatine foramen"],"factsHe":["עצם בצורת L","מכילה את הפורמן הפלטיני הגדול"],"diseases":["Cleft palate"],"diseasesHe":["חיך שסוע"]}'),
('skull', 'Mandible', 'Mandible', 'הלסת התחתונה', '🦷', 'jaw', '{"displayNameHe":"הלסת התחתונה","latinName":"Mandibula","function":"Lower jaw — chewing, speech, swallowing","functionHe":"הלסת התחתונה — לעיסה, דיבור, בליעה","facts":["Only movable bone in the skull","Holds all lower teeth"],"factsHe":["העצם היחידה בגולגולת שזזה","מחזיקה את כל השיניים התחתונות"],"diseases":["TMJ disorder","Mandible fracture"],"diseasesHe":["הפרעת מפרק הלסת","שבר בלסת התחתונה"]}'),
('skull', 'Teeth', 'Upper Teeth', 'שיניים עליונות', '🦷', 'jaw', '{"displayNameHe":"שיניים עליונות","latinName":"Dentes superiores","function":"Cutting and grinding food","functionHe":"חיתוך וטחינת מזון","facts":["32 permanent teeth in adults","Enamel is hardest substance in body"],"factsHe":["32 שיניים קבועות אצל מבוגר","האמייל הוא החומר הקשה ביותר בגוף"],"diseases":["Caries","Periodontitis"],"diseasesHe":["עששת","מחלת חניכיים"]}'),
('skull', 'Lower_teeth', 'Lower Teeth', 'שיניים תחתונות', '🦷', 'jaw', '{"displayNameHe":"שיניים תחתונות","latinName":"Dentes inferiores","function":"Biting and grinding food","functionHe":"נשיכה וטחינת מזון","facts":["Lower incisors erupt first"],"factsHe":["החותכות התחתונות בוקעות ראשונות"],"diseases":["Caries","Bruxism"],"diseasesHe":["עששת","חריקת שיניים"]}'),
('skull', 'Inferior_conchae', 'Inferior Nasal Conchae', 'קונכיות אפיות תחתונות', '😮', 'face', '{"displayNameHe":"קונכיות אפיות תחתונות","latinName":"Conchae nasales inferiores","function":"Warm, humidify, filter air","functionHe":"מחממות, מלחלחות ומסננות את האוויר","facts":["Only facial bone that is separate","Largest nasal turbinate"],"factsHe":["עצם הפנים היחידה שהיא עצם נפרדת","הקונכייה הגדולה ביותר באף"],"diseases":["Turbinate hypertrophy"],"diseasesHe":["היפרטרופיה של הקונכיות"]}'),
('skull', 'Vomer', 'Vomer', 'עצם מחיצת האף', '😮', 'face', '{"displayNameHe":"עצם מחיצת האף","latinName":"Vomer","function":"Forms inferior nasal septum","functionHe":"מהווה את החלק התחתון של מחיצת האף","facts":["Plough-shaped bone","Forms nasal septum"],"factsHe":["עצם בצורת מחרשה","מהווה חלק ממחיצת האף"],"diseases":["Deviated septum"],"diseasesHe":["סטיית מחיצת האף"]}'),

-- ═══ THORAX MODEL ═══
('thorax', 'Heart', 'Heart', 'הלב', '❤️', 'cardiovascular', '{"displayNameHe":"הלב","latinName":"Cor","function":"Pumps oxygenated blood through body","functionHe":"שואב דם עשיר בחמצן לכל הגוף","facts":["Beats ~100,000 times/day","Pumps ~5L blood/minute"],"factsHe":["פועם כ-100,000 פעמים ביום","שואב כ-5 ליטר דם בדקה"],"diseases":["Myocardial infarction","Heart failure","Arrhythmia"],"diseasesHe":["אוטם שריר הלב","אי-ספיקת לב","הפרעת קצב"]}'),
('thorax', 'Valves', 'Heart Valves', 'מסתמי הלב', '❤️', 'cardiovascular', '{"displayNameHe":"מסתמי הלב","latinName":"Valvae cordis","function":"Control one-directional blood flow","functionHe":"שולטים בזרימת דם חד-כיוונית דרך הלב","facts":["4 valves control blood flow","Open/close 100,000 times/day"],"factsHe":["4 מסתמים שולטים בזרימת הדם","נפתחים ונסגרים 100,000 פעם ביום"],"diseases":["Valve stenosis","Endocarditis"],"diseasesHe":["היצרות מסתמים","דלקת פנים הלב"]}'),
('thorax', 'Trachea', 'Trachea', 'קנה הנשימה', '💨', 'respiratory', '{"displayNameHe":"קנה הנשימה","latinName":"Trachea","function":"Airway from larynx to bronchi","functionHe":"נתיב אוויר מהגרון לסימפונות","facts":["15–20 C-shaped cartilage rings","Lined with cilia"],"factsHe":["15-20 טבעות סחוס בצורת C","מצופה בריסים שמסלקים ליחה"],"diseases":["Tracheomalacia","Tracheal stenosis"],"diseasesHe":["רפיון קנה הנשימה","היצרות קנה הנשימה"]}'),
('thorax', 'Lungs', 'Lungs', 'הריאות', '💨', 'respiratory', '{"displayNameHe":"הריאות","latinName":"Pulmones","function":"Gas exchange: O₂ in, CO₂ out","functionHe":"חילופי גזים: חמצן פנימה, פחמן דו-חמצני החוצה","facts":["Surface area ~70m² if unfolded","Right: 3 lobes, Left: 2 lobes"],"factsHe":["שטח פנים כ-70 מ\"ר אם נפרוש","ימנית: 3 אונות, שמאלית: 2 אונות"],"diseases":["Pneumonia","COPD","Lung cancer"],"diseasesHe":["דלקת ריאות","מחלת ריאות חסימתית","סרטן ריאות"]}'),
('thorax', 'Thorax', 'Thoracic Cage', 'כלוב הצלעות', '🦴', 'skeletal', '{"displayNameHe":"כלוב הצלעות","latinName":"Thorax","function":"Protective bony cage; aids breathing","functionHe":"כלוב עצם מגן; מסייע בנשימה","facts":["12 pairs of ribs + sternum","Protects heart and lungs"],"factsHe":["12 זוגות צלעות + עצם החזה","מגן על הלב והריאות"],"diseases":["Rib fracture","Costochondritis"],"diseasesHe":["שבר בצלע","דלקת סחוסי הצלעות"]}'),
('thorax', 'Thyroid_gland', 'Thyroid', 'בלוטת התריס', '🧪', 'glands', '{"displayNameHe":"בלוטת התריס","latinName":"Glandula thyroidea","function":"Regulates metabolism","functionHe":"מווסתת את חילוף החומרים","facts":["Butterfly-shaped gland","Produces T3 and T4"],"factsHe":["בלוטה בצורת פרפר","מייצרת הורמוני T3 ו-T4"],"diseases":["Hypothyroidism","Goiter"],"diseasesHe":["תת-פעילות בלוטת התריס","זפק"]}')

ON CONFLICT (mesh_key, model_url) DO UPDATE SET
  name = EXCLUDED.name,
  summary = EXCLUDED.summary,
  icon = EXCLUDED.icon,
  system = EXCLUDED.system,
  facts = EXCLUDED.facts,
  updated_at = now();
